[phases.setup]
# Install Python 3.11 AND pip (pip is a separate package in Nix)
nixPkgs = ["python311", "python311Packages.pip"]

[phases.install]
cmds = [
  # Use python -m pip (works even if 'pip' symlink is missing)
  "python -m pip install --upgrade pip setuptools wheel",
  "python -m pip install -r requirements.txt"
]

[phases.start]
cmd = "python bot_modular.py"
